#!/bin/bash

####################################################################
#Description:To setup TFPT server on Ubuntu
#Author: NamPham
#Email: nampt282@gmail.com
#Date: 2017_03_23
####################################################################
###################################################################

install_package(){
  sudo apt-get install xinetd tftpd tftp
}

config_tftpd(){
  local tftp_config="$1"
sudo bash -c "cat << EOF > $tftp_config
service tftp
{
protocol        = udp
port            = 69
socket_type     = dgram
wait            = yes
user            = nobody
server          = /usr/sbin/in.tftpd
server_args     = /tftpboot
disable         = no
}
EOF"
}

mkdir_tftpboot(){
  sudo mkdir -p /tftpboot
  sudo chmod -R 777 /tftpboot
  sudo chown -R nobody /tftpboot
}

test_tftpd(){
  local test_file="test_tftpd"
  local ip="127.0.0.1"
  echo "Create /tftpboot/$test_file  ..."
  sudo bash -c "echo whatever > /tftpboot/$test_file"
  echo "Type \"get ${test_file} \" then \"quit\" "
  tftp $ip
}


#Main
install_package
config_tftpd /etc/xinetd.d/tftp
mkdir_tftpboot
sudo service xinetd restart
test_tftpd
